### ISSUE TITLE
Check whether specific sorting is needed for toc

### ISSUE THREAD

**Issue by serenaf** [ember-learn/deprecation-app#15]
@locks is there a specific ordering you want if a specific version has multiple deprecations?

**Comment by locks** [comment]
@serenaf assume sort by id for a first version, if need-be we can add a manual index and change the sorting logic!

**Comment by jaredgalanis** [comment]
@serenaf @locks after bringing over the ember data files I'm realizing we need to revise the sorting because currently the CP uses the full versioning to sort (both major and minor). The issue with this is 2.10 will be listed before 2.3 because of the digits involved (i.e. 2.3 translates to 2.30 which is > 2.10). I have an idea for the sorting that focuses just on the minor version, which should sort things properly. I can open a PR on this in the next few days.

**Comment by acorncom** [comment]
@jaredgalanis there should be code for that type of sort in the api docs app too ...

**Comment by jaredgalanis** [comment]
Thanks @acorncom, I see that now. The `semver-compare` library is used there in the `getLastVersion` util, I'll be probably make use of `semver-compare` and borrow where needed from `getLastVersion`.

**Comment by mansona** [comment]
fixed in https://github.com/ember-learn/deprecation-app/pull/54
