### ISSUE TITLE
Rendering bug when rendering contents of version 2.0

### ISSUE THREAD

**Issue by serenaf** [ember-learn/deprecation-app#21]
I came across a rendering bug when adding content for the deprecations with since set to ```2.0```, see screenshot.

The generated data only contains ```  "since": 2,```

![screen shot 2018-01-15 at 22 49 03](https://user-images.githubusercontent.com/1288131/34964714-cb140712-fa46-11e7-83cc-45ff201ad1b2.png)

@mansona Would you have any idea why it is rendering in this way and it cannot read the 2.0?

**Comment by mansona** [comment]
I think we need to make since a string instead of a number.

and then we can sort using https://github.com/ember-learn/guides-app/blob/master/app/controllers/version.js#L14 which comes from https://github.com/ember-learn/guides-app/blob/master/package.json#L23 and https://github.com/ember-learn/guides-app/blob/master/ember-cli-build.js#L42
