### ISSUE TITLE
Add padding on the right when a `title` is really long

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/deprecation-app#85]
When a title is really long, add padding to the RHS. This is in the TOC on the LHS. 

![image](https://user-images.githubusercontent.com/1372946/36456897-2343ff74-165c-11e8-9efa-b5153dabe05d.png)

**Comment by amyrlam** [comment]
*I can work on this, just wanted to note it somewhere. (Or someone else can if wants to take it first!)

**Comment by yurikurant** [comment]
@amyrlam, @serenaf, currently this issue is resolved by the `word-wrap` rule in https://github.com/ember-learn/deprecation-app/blob/master/app/styles/app.scss#L84

![image](https://user-images.githubusercontent.com/465893/105890766-71396300-6018-11eb-9f8d-fd372c7ac16f.png)

should this ticket be closed now?

**Comment by amyrlam** [comment]
@yurikurant @serenaf thanks for pointing that out, much appreciated! closing the issue
